name: RDP Windows 10

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
      - name: Aktifkan RDP
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user github password123 /add
          net localgroup administrators github /add
          echo "RDP Aktif"
          ipconfig
          ping 127.0.0.1 -n 21600 >nul
